setwd("/Users/Dtrujillo/RCourse")
Data <- read.table("household_power_consumption.txt",header = TRUE, sep = ";",, na.strings = "?", colClasses = c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric'))
Data$Date <- as.Date(Data$Date, "%d/%m/%Y")
Data <- Data[complete.cases(Data),]
dateTime <- paste(Data$Date, Data$Time)

png(filename='plot4.png', width=480, height=480, units='px')

startDay = as.POSIXct(strftime("2007-02-01 00:00:00"))
endDay = as.POSIXct(strftime("2007-02-02 00:00:00"))
labels <- c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
columnlines <- c("black","red","blue")
par(mfrow=c(2,2))
plot(Data$Date, Data$Global_active_power, type="l", col="green", xlab="", ylab="Global Active Power")
plot(Data$Date, Data$Voltage, type="l", col="orange", xlab="datetime", ylab="Voltage")
plot(Data$Date, Data$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(Data$Date, Data$Sub_metering_2, type="l", col="red")
lines(Data$Date, Data$Sub_metering_3, type="l", col="blue")
legend("topright", bty="n", legend=labels, lty=1, col=columnlines)
plot(Data$Date, Data$Global_reactive_power, type="l", col="blue", xlab="datetime", ylab="Global_reactive_power")
